// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5f7cXTY6HUxNhF3bQFPNIf_N8pTZXm1A',
    appId: '1:476889456302:web:d7eb8901c6002ad480973f',
    messagingSenderId: '476889456302',
    projectId: 'chat-app-265d5',
    authDomain: 'chat-app-265d5.firebaseapp.com',
    storageBucket: 'chat-app-265d5.appspot.com',
    measurementId: 'G-BF22VTFRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzayOfPTP86YqE0qUgjZmlhLTx8vDaQg',
    appId: '1:476889456302:android:2b23536e57c2549080973f',
    messagingSenderId: '476889456302',
    projectId: 'chat-app-265d5',
    storageBucket: 'chat-app-265d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhwblAwTcOk-njnZVabapqhbhoJ17yaY',
    appId: '1:476889456302:ios:fc79188a7c69e12c80973f',
    messagingSenderId: '476889456302',
    projectId: 'chat-app-265d5',
    storageBucket: 'chat-app-265d5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhwblAwTcOk-njnZVabapqhbhoJ17yaY',
    appId: '1:476889456302:ios:d4bd015d359cd9a680973f',
    messagingSenderId: '476889456302',
    projectId: 'chat-app-265d5',
    storageBucket: 'chat-app-265d5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
